http:
  schema: http
  domain: localhost
  port: 80
database:
  dsn: mysql://root:toor@tcp(mysql)/main?collation=utf8mb4_general_ci&loc=Asia/Shanghai&parseTime=true
auth:
  key:
aliyunsms:
  appID:
  appSecret:
queue:
  size: 100
storage:
  path: ./storage
wechat:
  mini:
    appid:
    secret:
tcp:
  port: 10415
  msg:
    head: '{'
    foot: '}'